import React from 'react'
import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft,Layers,Edit3,LoaderCircle,Search,Save,X } from 'lucide-react'
import { supabase } from './lib/supabase'
export default function AdminDivisions({onBack}){
 const [rows,setRows]=useState([]),[companies,setCompanies]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false)
 async function load(){setLoading(true);setError('');const [d,c]=await Promise.all([supabase.from('divisions').select('id,company_id,division_name,division_code,description,status').order('division_name'),supabase.from('companies').select('id,company_name').order('company_name')]);if(d.error||c.error)setError((d.error||c.error).message);else{setRows(d.data||[]);setCompanies(c.data||[])}setLoading(false)}
 useEffect(()=>{load()},[])
 const cm=new Map(companies.map(x=>[x.id,x.company_name]));const filtered=useMemo(()=>rows.filter(x=>!q.trim()||[x.division_name,x.division_code,cm.get(x.company_id)].filter(Boolean).some(v=>v.toLowerCase().includes(q.toLowerCase()))),[rows,q,companies])
 function edit(x){setSelected(x);setForm({...x})}
 async function save(e){e.preventDefault();setBusy(true);const r=await supabase.from('divisions').update({company_id:form.company_id,division_name:form.division_name.trim(),division_code:form.division_code?.trim()||null,description:form.description?.trim()||null,status:form.status}).eq('id',selected.id).select('id,company_id,division_name,division_code,description,status').single();if(r.error)setError(r.error.message);else{setRows(x=>x.map(v=>v.id===r.data.id?r.data:v));setSelected(null)}setBusy(false)}
 return <div className="admin-page"><div className="admin-head"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={15}/> Dashboard</button><p className="section-kicker">ADMINISTRATION</p><h1>Divisions</h1><p>Manage company divisions and their identity.</p></div><button className="admin-refresh" onClick={load} disabled={loading}><LoaderCircle className={loading?'spin':''} size={15}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search division, code or company..."/></div></div><div className="admin-list-head"><strong>{filtered.length}</strong> divisions shown</div>{loading?<div className="admin-state">Loading divisions…</div>:<div className="admin-company-list">{filtered.map(x=><button className="admin-company-card" key={x.id} onClick={()=>edit(x)}><span className="admin-company-icon"><Layers size={18}/></span><span className="admin-company-copy"><strong>{x.division_name}</strong><span>{cm.get(x.company_id)||'Company not found'}</span><small>{x.division_code||'No division code'} • {x.status}</small></span><Edit3 size={15}/></button>)}</div>}{selected&&<div className="report-overlay"><div className="report-modal admin-edit-modal"><button className="report-close" onClick={()=>!busy&&setSelected(null)}><X size={18}/></button><p className="section-kicker">DIVISION RECORD</p><h2>Edit Division</h2><form onSubmit={save}><label>Company<select required value={form.company_id||''} onChange={e=>setForm({...form,company_id:e.target.value})}>{companies.map(x=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select></label><label>Division name<input required value={form.division_name||''} onChange={e=>setForm({...form,division_name:e.target.value})}/></label><label>Division code<input value={form.division_code||''} onChange={e=>setForm({...form,division_code:e.target.value})}/></label><label>Description<textarea rows="3" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Status<select value={form.status||'active'} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className="report-submit" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/> Saving…</>:<><Save size={16}/> Save Changes</>}</button></form></div></div>}</div>
}