import React from 'react'
import { useEffect,useState } from 'react'
import { ArrowLeft,ShieldCheck,Clock3,LoaderCircle,RefreshCw } from 'lucide-react'
import { supabase } from './lib/supabase'
export default function AdminVerification({onBack}){
 const [rows,setRows]=useState([]),[filter,setFilter]=useState('needs_review'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState('')
 async function load(){setLoading(true);const r=await supabase.from('distributorships').select('id,company_id,distributor_id,division_id,territory,verification_status,verification_note,verification_notes').eq('status','active').order('created_at',{ascending:false});if(r.error){setError(r.error.message);setLoading(false);return}const idsC=[...new Set((r.data||[]).map(x=>x.company_id))],idsD=[...new Set((r.data||[]).map(x=>x.distributor_id))],idsV=[...new Set((r.data||[]).map(x=>x.division_id).filter(Boolean))];const [c,d,v]=await Promise.all([idsC.length?supabase.from('companies').select('id,company_name').in('id',idsC):Promise.resolve({data:[],error:null}),idsD.length?supabase.from('distributors').select('id,distributor_name').in('id',idsD):Promise.resolve({data:[],error:null}),idsV.length?supabase.from('divisions').select('id,division_name').in('id',idsV):Promise.resolve({data:[],error:null})]);if(c.error||d.error||v.error){setError((c.error||d.error||v.error).message)}else{const cm=new Map((c.data||[]).map(x=>[x.id,x.company_name])),dm=new Map((d.data||[]).map(x=>[x.id,x.distributor_name])),vm=new Map((v.data||[]).map(x=>[x.id,x.division_name]));setRows((r.data||[]).map(x=>({...x,company_name:cm.get(x.company_id),distributor_name:dm.get(x.distributor_id),division_name:x.division_id?vm.get(x.division_id):null})))}setLoading(false)}
 useEffect(()=>{load()},[])
 async function setStatus(id,status){setSaving(id);const now=status==='verified'?new Date().toISOString().slice(0,10):null;const r=await supabase.from('distributorships').update({verification_status:status,verified_date:now,verified_at:status==='verified'?new Date().toISOString():null}).eq('id',id);if(r.error)setError(r.error.message);else setRows(x=>x.map(v=>v.id===id?{...v,verification_status:status,verified_date:now}:v));setSaving('')}
 const shown=rows.filter(x=>filter==='all'||x.verification_status===filter)
 return <div className="admin-page"><div className="admin-head"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={15}/> Dashboard</button><p className="section-kicker">ADMINISTRATION</p><h1>Verification</h1><p>Review and update distributorship verification status.</p></div><button className="admin-refresh" onClick={load}><RefreshCw size={15}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-toolbar"><div className="admin-filters">{['needs_review','unverified','verified','all'].map(x=><button className={filter===x?'selected':''} key={x} onClick={()=>setFilter(x)}>{x.replace('_',' ')}</button>)}</div></div><div className="admin-list-head"><strong>{shown.length}</strong> relationships shown</div>{loading?<div className="admin-state"><LoaderCircle className="spin" size={20}/> Loading verification queue…</div>:<div className="admin-company-list">{shown.map(x=><div className="admin-company-card" key={x.id}><span className="admin-company-icon">{x.verification_status==='verified'?<ShieldCheck size={18}/>:<Clock3 size={18}/>}</span><span className="admin-company-copy"><strong>{x.company_name||'Company'}</strong><span>{x.distributor_name||'Distributor'}{x.division_name?' • '+x.division_name:''}</span><small>{x.territory||'Kutch territory not specified'} • {x.verification_status}</small></span><div className="admin-actions-inline">{x.verification_status!=='verified'&&<button onClick={()=>setStatus(x.id,'verified')} disabled={saving===x.id}>Verify</button>}{x.verification_status!=='needs_review'&&<button onClick={()=>setStatus(x.id,'needs_review')} disabled={saving===x.id}>Review</button>}</div></div>)}</div>}</div>
}