import React,{useEffect,useMemo,useState} from 'react'
import {ArrowLeft,Tags,LoaderCircle,Search,Save,X} from 'lucide-react'
import {supabase} from './lib/supabase'

export default function AdminBrands({onBack}){
 const [rows,setRows]=useState([]),[companies,setCompanies]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false)
 async function load(){setLoading(true);setError('');const [b,c]=await Promise.all([supabase.from('brands').select('id,company_id,brand_name,description,status').order('brand_name'),supabase.from('companies').select('id,company_name').eq('status','active').order('company_name')]);const bad=[b,c].find(x=>x.error);if(bad)setError(bad.error.message);else{setRows(b.data||[]);setCompanies(c.data||[])}setLoading(false)}
 useEffect(()=>{load()},[])
 const cm=new Map(companies.map(x=>[x.id,x.company_name]))
 const filtered=useMemo(()=>rows.filter(x=>!q.trim()||[x.brand_name,cm.get(x.company_id)].filter(Boolean).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))),[rows,q,companies])
 function edit(x){setSelected(x);setForm({...x})}
 async function save(e){e.preventDefault();setBusy(true);setError('');const r=await supabase.from('brands').update({company_id:form.company_id,brand_name:form.brand_name.trim(),description:form.description?.trim()||null,status:form.status||'active'}).eq('id',selected.id).select('id,company_id,brand_name,description,status').single();if(r.error)setError(r.error.message);else{setRows(x=>x.map(v=>v.id===r.data.id?r.data:v));setSelected(null)}setBusy(false)}
 return <div className="admin-page"><div className="admin-head"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={15}/> Dashboard</button><p className="section-kicker">DIRECTORY STRUCTURE</p><h1>Brands</h1><p>Brands are child records of a company. Do not create a new company for a brand.</p></div><button className="admin-refresh" onClick={load} disabled={loading}><LoaderCircle className={loading?'spin':''} size={15}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-info-box"><strong>Data rule</strong><span>Example: Procter & Gamble is one company. Vicks, Head & Shoulders and other marketed names can be brands under that company. A company can also belong to multiple categories.</span></div><div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search brand or company..."/></div></div><div className="admin-list-head"><strong>{filtered.length}</strong> brands shown</div>{loading?<div className="admin-state"><LoaderCircle className="spin" size={20}/> Loading brands…</div>:<div className="admin-company-list">{filtered.map(x=><button className="admin-company-card" key={x.id} onClick={()=>edit(x)}><span className="admin-company-icon"><Tags size={18}/></span><span className="admin-company-copy"><strong>{x.brand_name}</strong><span>{cm.get(x.company_id)||'Company not found'}</span><small>{x.status}{x.description?' • '+x.description:''}</small></span></button>)}</div>}{selected&&<div className="report-overlay"><div className="report-modal admin-edit-modal"><button className="report-close" onClick={()=>!busy&&setSelected(null)}><X size={18}/></button><p className="section-kicker">BRAND RECORD</p><h2>Edit Brand</h2><form onSubmit={save}><label>Parent company<select required value={form.company_id||''} onChange={e=>setForm({...form,company_id:e.target.value})}>{companies.map(x=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select></label><label>Brand name<input required value={form.brand_name||''} onChange={e=>setForm({...form,brand_name:e.target.value})}/></label><label>Description<textarea rows="3" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Status<select value={form.status||'active'} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className="report-submit" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/> Saving…</>:<><Save size={16}/> Save Changes</>}</button></form></div></div>}</div>
}
