import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft,Tags,LoaderCircle,Search,Save,X } from 'lucide-react'
import { supabase } from './lib/supabase'
export default function AdminAliases({onBack}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false)
 async function load(){setLoading(true);setError('');const r=await supabase.from('search_aliases').select('id,entity_type,entity_id,alias,normalized_alias').order('alias');if(r.error)setError(r.error.message);else setRows(r.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(x=>!q.trim()||[x.alias,x.normalized_alias,x.entity_type].filter(Boolean).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))),[rows,q])
 function edit(x){setSelected(x);setForm({...x})}
 async function save(e){e.preventDefault();setBusy(true);const alias=form.alias.trim();const r=await supabase.from('search_aliases').update({alias,normalized_alias:alias.toLowerCase().trim().replace(/\\s+/g,' ')}).eq('id',selected.id).select('id,entity_type,entity_id,alias,normalized_alias').single();if(r.error)setError(r.error.message);else{setRows(x=>x.map(v=>v.id===r.data.id?r.data:v));setSelected(null)}setBusy(false)}
 return <div className="admin-page"><div className="admin-head"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={15}/> Dashboard</button><p className="section-kicker">ADMINISTRATION</p><h1>Search Aliases</h1><p>Manage alternate names used by directory search.</p></div><button className="admin-refresh" onClick={load} disabled={loading}><LoaderCircle className={loading?'spin':''} size={15}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search alias or entity type..."/></div></div><div className="admin-list-head"><strong>{filtered.length}</strong> aliases shown</div>{loading?<div className="admin-state">Loading aliases…</div>:<div className="admin-company-list">{filtered.map(x=><button className="admin-company-card" key={x.id} onClick={()=>edit(x)}><span className="admin-company-icon"><Tags size={18}/></span><span className="admin-company-copy"><strong>{x.alias}</strong><span>{x.entity_type}</span><small>{x.normalized_alias}</small></span></button>)}</div>}{selected&&<div className="report-overlay"><div className="report-modal admin-edit-modal"><button className="report-close" onClick={()=>!busy&&setSelected(null)}><X size={18}/></button><p className="section-kicker">SEARCH ALIAS</p><h2>Edit Alias</h2><form onSubmit={save}><label>Alias<input required value={form.alias||''} onChange={e=>setForm({...form,alias:e.target.value})}/></label><label>Entity type<input disabled value={form.entity_type||''}/></label><label>Entity ID<input disabled value={form.entity_id||''}/></label><button className="report-submit" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/> Saving…</>:<><Save size={16}/> Save Changes</>}</button></form></div></div>}</div>
}