import { useRef,useState } from 'react'
import { ArrowLeft,Download,Upload,Database,FileJson,LoaderCircle } from 'lucide-react'
import { supabase } from './lib/supabase'
const tables=['companies','distributors','divisions','categories','locations','distributorships','search_aliases','company_categories']
export default function AdminTools({onBack}){
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),fileRef=useRef(null)
 async function exportTable(name){setBusy(name);setError('');const r=await supabase.from(name).select('*');if(r.error)setError(name+': '+r.error.message);else{const blob=new Blob([JSON.stringify(r.data||[],null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kutchpharmaconnect-'+name+'-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);setMessage('Exported '+name+'.')}setBusy('')}
 async function exportAll(){setBusy('all');setError('');const out={exported_at:new Date().toISOString(),tables:{}};for(const t of tables){const r=await supabase.from(t).select('*');if(r.error){setError(t+': '+r.error.message);setBusy('');return}out.tables[t]=r.data||[]}const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kutchpharmaconnect-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);setMessage('Full JSON backup exported.')} 
 function importNotice(e){const f=e.target.files?.[0];if(!f)return;setMessage('Selected '+f.name+'. Import is intentionally not automatic; review data before database changes.');e.target.value=''}
 return <div className="admin-page"><div className="admin-head"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={15}/> Dashboard</button><p className="section-kicker">DATA TOOLS</p><h1>Import, Export & Backup</h1><p>Export production data and prepare files for controlled imports.</p></div></div>{error&&<div className="admin-error">{error}</div>}{message&&<div className="admin-note admin-message">{message}</div>}<div className="admin-tool-grid"><section className="admin-panel"><p className="section-kicker">BACKUP</p><h2>Full database export</h2><p className="admin-help">Downloads the current directory tables as JSON. This is a data backup, not a Supabase infrastructure backup.</p><button className="admin-tool-button" onClick={exportAll} disabled={busy}><Database size={16}/>{busy==='all'?<><LoaderCircle className="spin" size={16}/> Exporting…</>:'Download full JSON backup'}</button></section><section className="admin-panel"><p className="section-kicker">EXPORT</p><h2>Individual tables</h2>{tables.map(t=><button className="admin-tool-row" key={t} onClick={()=>exportTable(t)} disabled={busy}><FileJson size={15}/><span>{t}</span><Download size={14}/></button>)}</section><section className="admin-panel"><p className="section-kicker">IMPORT</p><h2>Controlled import</h2><p className="admin-help">Select a JSON file for review. No records are written automatically.</p><input ref={fileRef} type="file" accept=".json" hidden onChange={importNotice}/><button className="admin-tool-button" onClick={()=>fileRef.current?.click()}><Upload size={16}/> Select JSON file</button></section></div></div>
}