import React from 'react'
import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft,MapPin,Edit3,LoaderCircle,Search,Save,X } from 'lucide-react'
import { supabase } from './lib/supabase'
export default function AdminLocations({onBack}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false)
 async function load(){setLoading(true);const r=await supabase.from('locations').select('id,city,district,state,pincode').order('city');if(r.error)setError(r.error.message);else setRows(r.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(x=>!q.trim()||[x.city,x.district,x.state,x.pincode].filter(Boolean).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))),[rows,q])
 function edit(x){setSelected(x);setForm({...x})}
 async function save(e){e.preventDefault();setBusy(true);const r=await supabase.from('locations').update({city:form.city.trim(),district:form.district?.trim()||null,state:form.state?.trim()||null,pincode:form.pincode?.trim()||null}).eq('id',selected.id).select('id,city,district,state,pincode').single();if(r.error)setError(r.error.message);else{setRows(x=>x.map(v=>v.id===r.data.id?r.data:v));setSelected(null)}setBusy(false)}
 return <div className="admin-page"><div className="admin-head"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={15}/> Dashboard</button><p className="section-kicker">ADMINISTRATION</p><h1>Locations</h1><p>Manage Kutch directory locations.</p></div><button className="admin-refresh" onClick={load} disabled={loading}><LoaderCircle className={loading?'spin':''} size={15}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, district, state or pincode..."/></div></div><div className="admin-list-head"><strong>{filtered.length}</strong> locations shown</div>{loading?<div className="admin-state">Loading locations…</div>:<div className="admin-company-list">{filtered.map(x=><button className="admin-company-card" key={x.id} onClick={()=>edit(x)}><span className="admin-company-icon"><MapPin size={18}/></span><span className="admin-company-copy"><strong>{x.city||'Unnamed location'}</strong><span>{x.district||''}</span><small>{x.state||''}{x.pincode?' • '+x.pincode:''}</small></span><Edit3 size={15}/></button>)}</div>}{selected&&<div className="report-overlay"><div className="report-modal admin-edit-modal"><button className="report-close" onClick={()=>!busy&&setSelected(null)}><X size={18}/></button><p className="section-kicker">LOCATION RECORD</p><h2>Edit Location</h2><form onSubmit={save}><label>City<input required value={form.city||''} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>District<input value={form.district||''} onChange={e=>setForm({...form,district:e.target.value})}/></label><label>State<input value={form.state||''} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>Pincode<input value={form.pincode||''} onChange={e=>setForm({...form,pincode:e.target.value})}/></label><button className="report-submit" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/> Saving…</>:<><Save size={16}/> Save Changes</>}</button></form></div></div>}</div>
}