import React from 'react'
import { useEffect,useState } from 'react'
import { ArrowLeft,Tags,LoaderCircle,Search,Save,X } from 'lucide-react'
import { supabase } from './lib/supabase'
export default function AdminCategories({onBack}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[name,setName]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setLoading(true);const r=await supabase.from('categories').select('*').order('name');if(r.error)setError(r.error.message);else setRows(r.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const filtered=rows.filter(x=>!q.trim()||String(x.name||x.category_name||'').toLowerCase().includes(q.toLowerCase()))
 function edit(x){setSelected(x);setName(x.category_name||x.name||'')}
 async function save(e){e.preventDefault();setBusy(true);setError('');const key=selected.name!==undefined?'name':'category_name';const r=await supabase.from('categories').update({[key]:name.trim()}).eq('id',selected.id).select('*').single();if(r.error)setError(r.error.message);else{setRows(x=>x.map(v=>v.id===r.data.id?r.data:v));setSelected(null)}setBusy(false)}
 return <div className="admin-page"><div className="admin-head"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={15}/> Dashboard</button><p className="section-kicker">ADMINISTRATION</p><h1>Categories</h1><p>Manage directory category labels.</p></div><button className="admin-refresh" onClick={load} disabled={loading}><LoaderCircle className={loading?'spin':''} size={15}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search categories..."/></div></div><div className="admin-list-head"><strong>{filtered.length}</strong> categories shown</div>{loading?<div className="admin-state">Loading categories…</div>:<div className="admin-company-list">{filtered.map(x=><div className="admin-company-card" key={x.id}><span className="admin-company-icon"><Tags size={18}/></span><span className="admin-company-copy"><strong>{x.category_name||x.name}</strong><small>{x.description||'Directory category'}</small></span><button className="admin-actions-inline" onClick={()=>edit(x)}>Edit</button></div>)}</div>}{selected&&<div className="report-overlay"><div className="report-modal admin-edit-modal"><button className="report-close" onClick={()=>!busy&&setSelected(null)}><X size={18}/></button><p className="section-kicker">CATEGORY</p><h2>Edit Category</h2><form onSubmit={save}><label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><button className="report-submit" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/> Saving…</>:<><Save size={16}/> Save Changes</>}</button></form></div></div>}</div>
}